module.exports = {
    beforeEach: browser => {
        browser.url('https://alpha.yoodlize.com/')
    },
    after: browser => {
        browser.end()
    },
    'My tests': browser => {
        browser
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[1]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Recreational Vehicles")
        .pause(300)  
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[2]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Outdoor Gear")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[3]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Electronics")
        .pause(300) 
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[4]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Party & Wedding Equipment")
        .pause(300) 
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[5]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Tools")
        .pause(300) 
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[6]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Clothing")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[7]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Home and Kitchen")
        .pause(300) 
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[8]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Toys and Games")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[9]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Lawn and Garden")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[10]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Sporting Equipment")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[11]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "DVDs")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[12]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Venues")
        .pause(300) 
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[13]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Music")
        .pause(300)  
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[14]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Business Equipment")
        .pause(300) 
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK djSgtl sc-gqjmRU fmVgeN"])[15]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Misc")
        .pause(300)
    },
    'Test 2': browser => {
        browser
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[1]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Tools")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[2]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Outdoor Gear")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[3]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Electronics")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[4]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Party & Wedding Equipment")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[5]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Recreational Vehicles")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[6]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Clothing")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[7]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Home and Kitchen")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[8]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Toys and Games")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[9]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Lawn and Garden")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[10]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Sporting Equipment")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[11]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "DVDs")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[12]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Venues")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[13]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Music")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
        .useXpath()
        .click('(//div[@class="sc-jqCOkK MvxJP sc-gqjmRU ksayja"])[14]')
        .useCss()
        .verify.containsText('[class="sc-jKVCRD jSqgxr"]', "Misc")
        .pause(300)
        .click('[src="/images/logo/blueRaw.png"]')
    },
    'Test 3': browser => {
        browser
            .setValue('.form-control', "Canoe")
            .verify.value('.form-control', "Canoe")
            .keys(browser.Keys.ENTER)
            .waitForElementVisible('#keyword-search-input')
            .useXpath()
            .click('(//div[@id="card-title"])[1]')
            .verify.urlContains('details/783')
            .pause(700)


    }
}